# Generated by Django 3.2.25 on 2025-01-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250102_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
